### ISSUE TITLE
跳跃错误

### ISSUE THREAD

**Issue by zlog-in** [jjyr/mmr.py#1]
> 父节点和左子节点 offset 为 2 ** height
> 兄弟节点间的 offset 为 2 ** (height + 1) - 1

代码运算 `2^height`应该是
```
1  <<  height
````
而不是
```
2 << height
```

**Comment by zlog-in** [comment]
by the way, I've found another manipulation for mmr. I'll share with you later.

**Comment by jjyr** [comment]
https://github.com/jjyr/mmr.py/commit/348c0c66b387f0fc5babd260be2f015b67656fc2

`2 ** (height + 1) - 1` -> `(2 << height) - 1`

**Comment by zlog-in** [comment]
Thanks for your explanation. I got another problem and opened a new issue for help.
