### ISSUE TITLE
meaning of mmr_size

### ISSUE THREAD

**Issue by zlog-in** [jjyr/mmr.py#2]
```python
def get_peaks(mmr_size) -> List[int]:
    """
    return peaks positions from left to right
    """
    def get_right_peak(height, pos, mmr_size):
        """
        find next right peak
        peak not exsits if height is -1
        """
        # jump to right sibling
        pos += sibling_offset(height)
        # jump to left child
        while pos > mmr_size - 1:
            height -= 1
            if height < 0:
                # no right peak exists
                return (height, None)
            pos -= 2 << height
        return (height, pos)

    poss = []
    height, pos = left_peak_height_pos(mmr_size)
    poss.append(pos)
    while height > 0:
        height, pos = get_right_peak(height, pos, mmr_size)
        if height >= 0:
            poss.append(pos)
    return poss
```

Hello, there is a function named `get_peaks(mmr_size)` in your code, which finds position of all peaks, that function is called in line 183, the argument is `self.last_pos+1`, that means number of all nodes(not only leaves) in mmr. 

And `get_peaks()` calls an another function `left_peak_height_pos(mmr_size)`, which returns the height and position of the most left peak. 

But in function `left_peak_height_pos(mmr_size)`,  for determining the height of that peak, the mmr_size for iteration stopping is the number of leaves, is that right?

So I feel confused the meaning  the argument  for `left_peak_height_pos()` when function `get_peaks()` calling it.

**Comment by jjyr** [comment]
> But in function left_peak_height_pos(mmr_size), for determining the height of that peak, the mmr_size for iteration stopping is the number of leaves, is that right?

No, `left_peak_height_pos` calculate the position of the peak element for each height, if the position is large than mmr_size, we stop the iteration and return the last hight.

**Comment by zlog-in** [comment]
I understood the returns from `left_peak_height_pos()`. I just didn't know what mmr_size does mean. All nodes in mmr or just leaf nodes? It may be a stupid question, but I truly feel missed.

**Comment by jjyr** [comment]
all nodes and leaves in the tree

**Comment by zlog-in** [comment]
You mean sometime mmr_size represents all nodes(leaves + inner nodes) and sometime mmr_size is just number of leaves? I feel doubt cuz we could determine the most left peak height just with the number of leaves according the the following relation
> 2 ** h -1 <= N, N is number of leaves
the biggest value for h satisfying that relation is the height for the most left peak.

**Comment by jjyr** [comment]
> 2 ** h -1 <= N

In this expression, N means the count of all nodes in the tree if the tree has exactly `N'` leaves.

**Comment by zlog-in** [comment]
Thanks for you explanation and kindness. Here I find another manipulation for mmr in Golang. In this version the number of leaves is presented in binary and it's easy to understand that the 1-bits is a mark for a peak and the weight 2^n(n= 0, 1, ...) of that 1-bits is the size of that peak.

[minPeakHeight](https://github.com/zhiqiangxu/util/blob/e44faa570cf9b7c50d8977cab25d025f4b9cbe67/mmr/util.go#L9)
[maxPeakHeight](https://github.com/zhiqiangxu/util/blob/e44faa570cf9b7c50d8977cab25d025f4b9cbe67/mmr/util.go#L13)
[peakSize](https://github.com/zhiqiangxu/util/blob/e44faa570cf9b7c50d8977cab25d025f4b9cbe67/mmr/util.go#L19)
[leftPeak](https://github.com/zhiqiangxu/util/blob/e44faa570cf9b7c50d8977cab25d025f4b9cbe67/mmr/util.go#L36)
...
